# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{group_by_hash}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Boone"]
  s.date = %q{2010-07-22}
  s.description = %q{A ruby hash with a sql-esque group by method for when you can't do a group by in SQL because it is too complicated
}
  s.email = %q{paulboone@mindbucket.com}
  s.files = [
    "Rakefile",
     "VERSION",
     "lib/group_by_hash.rb",
     "spec/group_by_hash_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/paulboone/group_by_hash}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{ruby hash with a sql-esque group by method}
  s.test_files = [
    "spec/group_by_hash_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

